### ISSUE TITLE
Hey bro, does it work already?

### ISSUE THREAD

**Issue by TKForgeron** [0xMDIV/Webm-To-MP4-Converter-Python#1]
bc for me it wont, only gives :
transformating, please wait...
Subprocess Failed Converting

**Comment by 0xMDIV** [comment]
Do you have FFMPEG installed?
If not install it by Downloading it from: https://ffmpeg.org/download.html
And make a Folder on your System Drive (mine is C:\) ffmpeg and copy into that folder the files you downloaded

If that doesnt work, try to run the script as Administrator

**Comment by 0xMDIV** [comment]
No further replies, closing it

**Comment by TKForgeron** [comment]
Ah i see, great, thanks!
